#Begin: Configmap
#data source: https://www.kaggle.com/luiscorter/netflix-original-films-imdb-scores
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-deployment-init-configmap
data:
  mysql-init.sql: |
    CREATE TABLE `movie` (
      `movie_name` VARCHAR(100) NOT NULL,
      `genre`  VARCHAR(45),
      `language` VARCHAR(30),
      PRIMARY KEY (`movie_name`)
    );

    CREATE TABLE `favourite` (
      `movie_name` VARCHAR(100) NOT NULL,
      `genre` VARCHAR(45) NOT NULL,
      `count` BIGINT,
       PRIMARY KEY (`movie_name`)
    );

    
    INSERT INTO movie (movie_name, genre, language) VALUES ('Enter_the_Anime', 'Documentary', 'English/Japanese');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Searching_for_Sheela', 'Documentary', 'English');
    INSERT INTO movie (movie_name, genre, language) VALUES ('After_the_Raid', 'Documentary', 'Spanish');
    INSERT INTO movie (movie_name, genre, language) VALUES ('After_Maria', 'Documentary', 'English/Spanish');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Out_of_Many', 'Documentary', 'English');

    INSERT INTO movie (movie_name, genre, language) VALUES ('Dark_Forces', 'Thriller','Spanish');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Rebirth', 'Thriller','English');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Clinical', 'Thriller','English');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Dangerous_Lies', 'Thriller','English');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Hold_the_Dark', 'Thriller','English');
   

    INSERT INTO movie (movie_name, genre, language) VALUES ('Leyla_Everlasting', 'Comedy', 'English');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Seriously_Single', 'Comedy', 'English');
    INSERT INTO movie (movie_name, genre, language) VALUES ('The_Misadventures_of_Hedi_and_Cokeman', 'Comedy', 'French');
    INSERT INTO movie (movie_name, genre, language) VALUES ('5_Star_Christmas', 'Comedy', 'Italian');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Take_the_10', 'Comedy', 'English');

    INSERT INTO movie (movie_name, genre, language) VALUES ('Point_Blank', 'Action', 'English');
    INSERT INTO movie (movie_name, genre, language) VALUES ('The_Do-Over', 'Action', 'English');
    INSERT INTO movie (movie_name, genre, language) VALUES ('6_Underground', 'Action', 'English');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Spenser_Confidential', 'Action', 'English');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Polar', 'Action', 'English');

    INSERT INTO movie (movie_name, genre, language) VALUES ('The_Forest_of_Love', 'Drama', 'Japanese');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Uncorked', 'Drama', 'English');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Irreplaceable_You', 'Drama', 'English');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Street_Flow', 'Drama', 'French');
    INSERT INTO movie (movie_name, genre, language) VALUES ('All_Together_Now', 'Drama', 'English');

    INSERT INTO movie (movie_name, genre, language) VALUES ('I_Am_the_Pretty_Thing_That_Lives_in_the_House', 'Horror', 'English');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Rattlesnake', 'Horror', 'English');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Nobody_Sleeps_in_the_Woods_Tonight', 'Horror', 'Polish');
    INSERT INTO movie (movie_name, genre, language) VALUES ('Things_Heard_&_Seen', 'Horror', 'English');
    INSERT INTO movie (movie_name, genre, language) VALUES ('In_the_Tall_Grass', 'Horror', 'English');







---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: my-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mysql
  template:
    metadata:
      labels:
        app: my-mysql
    spec:
      # Mount the configmap volume
      # This is an excerpt of deployment.spec.template.spec
      volumes:
        - name: init-volume
          configMap:
            name: mysql-deployment-init-configmap
      containers:
        - name: my-mysql
          image: mysql
          volumeMounts:
            - name: init-volume
              mountPath: /docker-entrypoint-initdb.d/
          # Set required environment variables to initialize the container
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mysecretpw"
            - name: MYSQL_DATABASE
              value: "popular"
          ports:
            - containerPort: 33060

---
#Begin: Service
apiVersion: v1
kind: Service
metadata:
  name: my-app-mysql-service
spec:
  selector:
    app: my-mysql
  ports:
    - name: mysql-xproto
      protocol: TCP
      port: 33060
      targetPort: 33060
#End: Service
