#Begin: Configmap
#data source: https://www.kaggle.com/luiscorter/netflix-original-films-imdb-scores

# Create two tables (movies and popular), which contain descriptive attributes for our movies and further calculations

# Table which stores the movie data


# Table which stores the information on how often a movie is selected by the user

# Filling the movies table with data respectively
# Data used is derived from a Netflix DB from Kaggle (see link above)
# Contains a picture of each movie, which is displayed on the Web App


# yaml configurations for mysql database

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-deployment-init-configmap
data:
  mysql-init.sql: |

    CREATE TABLE `movies` (
      `movie` VARCHAR(100) NOT NULL,
      `genre`  VARCHAR(45),
      `language` VARCHAR(30),
      `image` VARCHAR(100),
      `linksource` VARCHAR(500),
      PRIMARY KEY (`movie`)
    );

    CREATE TABLE `popular` (
      `movie` VARCHAR(100) NOT NULL,
      `count` BIGINT,
       PRIMARY KEY (`movie`)
    );


    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Enter_the_Anime', 'Documentary', 'English/Japanese', 'Enter_the_Anime.jpg', 'https://www.film-rezensionen.de/wp-content/uploads/2019/08/Enter-the-Anime-214x300.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Searching_for_Sheela', 'Documentary', 'English', 'Searching_for_Sheela.jpg', 'https://de.web.img2.acsta.net/c_310_420/pictures/21/04/16/14/48/0425567.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('After_the_Raid', 'Documentary', 'Spanish', 'After_the_Raid.jpg', 'https://m.media-amazon.com/images/M/MV5BNzBlNGI1ZjEtYjljMC00ZThhLWJmNzktMTViZWZmZDRjNzNjXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('After_Maria', 'Documentary', 'English/Spanish', 'After_Maria.jpg', 'https://m.media-amazon.com/images/M/MV5BYzMzZTdkMTMtODk2Ni00NGNhLThkODYtYTBjOGMwYjE2OTU2XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Out_of_Many', 'Documentary', 'English', 'Out_of_Many.jpg', 'https://i.pinimg.com/564x/77/8e/05/778e0543ea9fe0fbce00ce56a790b27a.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Dark_Forces', 'Thriller','Spanish', 'Dark_Forces.jpg', 'https://m.media-amazon.com/images/M/MV5BYTVkNjQ3YTYtNmQxYi00ZWMwLTgyMjQtMzkxMWQ0NTNhMDY4XkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Rebirth', 'Thriller','English', 'Rebirth.jpg', 'https://assets.cdn.moviepilot.de/files/e6d3f145722e617f00cedb7818bfab9380dcf61b4b7b344dc00d18a736bd/limit/500/1000/rebirth.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Clinical', 'Thriller','English', 'Clinical.jpg', 'https://m.media-amazon.com/images/M/MV5BMjMzNTkwNzMyMF5BMl5BanBnXkFtZTgwNTg2MzIxMTI@._V1_.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Dangerous_Lies', 'Thriller','English', 'Dangerous_Lies.jpg', 'https://m.media-amazon.com/images/M/MV5BMDRjMmUzMTEtMWJiMC00MDUwLWExOGQtNDU2ZTU0Y2RmY2YzXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Hold_the_Dark', 'Thriller','English', 'Hold_the_Dark.jpeg', 'https://upload.wikimedia.org/wikipedia/en/e/ec/Hold_the_Dark.jpeg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Leyla_Everlasting', 'Comedy', 'English', 'Leyla_Everlasting.jpg', 'https://m.media-amazon.com/images/M/MV5BNTFlMzg3NDEtNTAxYi00ZDA3LTg4NDctMzVkZDRhNmZiMWNlXkEyXkFqcGdeQXVyMTA0NTY3NDQx._V1_.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Seriously_Single', 'Comedy', 'English', 'Seriously_Single.jpg', 'https://de.web.img3.acsta.net/pictures/20/06/25/11/37/5669880.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('The_Misadventures_of_Hedi_and_Cokeman', 'Comedy', 'French', 'The_Misadventures_of_Hedi_and_Cokeman.jpg', 'https://upload.wikimedia.org/wikipedia/en/7/72/En-passant-pecho-les-carottes-sont-cuites-french-movie-poster-md.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('5_Star_Christmas', 'Comedy', 'Italian', '5_Star_Christmas.jpg', 'https://flxt.tmsimg.com/assets/p16332031_p_v8_aa.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Take_the_10', 'Comedy', 'English', 'Take_the_10.jpg', 'https://m.media-amazon.com/images/M/MV5BN2E1YmYwOTAtMjdkNS00ZGJjLTk3MmQtYzZkNWQwNmM0Mjg5L2ltYWdlXkEyXkFqcGdeQXVyMzMxODMxNjk@._V1_.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Point_Blank', 'Action', 'English', 'Point_Blank.jpg', 'https://de.web.img2.acsta.net/pictures/19/07/03/16/40/1358466.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('The_Do-Over', 'Action', 'English', 'The_Do-Over.png', 'https://de.web.img2.acsta.net/pictures/16/04/21/13/06/114721.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('6_Underground', 'Action', 'English', '6_Underground.jpg', 'https://resizing.flixster.com/JAyeGOB1z7t5aVS8N-cXK_ZFm_k=/ems.ZW1zLXByZC1hc3NldHMvbW92aWVzL2Y0ZTlhNjlkLWFhMTctNDQ5Yy05MDZmLTQ3NzdlZWUzOGRkNy53ZWJw');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Spenser_Confidential', 'Action', 'English', 'Spenser_Confidential.jpg', 'https://de.web.img3.acsta.net/pictures/20/01/21/07/49/3503136.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Polar', 'Action', 'English', 'Polar.jpeg', 'https://de.web.img3.acsta.net/pictures/19/01/07/17/18/4980802.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('The_Forest_of_Love', 'Drama', 'Japanese', 'The_Forest_of_Love.jpg', 'https://upload.wikimedia.org/wikipedia/en/0/06/The_Forest_of_Love.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Uncorked', 'Drama', 'English', 'Uncorked.jpge', 'https://de.web.img2.acsta.net/pictures/20/03/25/19/34/3442733.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Irreplaceable_You', 'Drama', 'English', 'Irreplaceable_You.jpg', 'https://upload.wikimedia.org/wikipedia/en/1/17/Irreplaceable_You.png');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Street_Flow', 'Drama', 'French', 'Street_Flow.jpg', 'https://upload.wikimedia.org/wikipedia/en/f/fa/Banlieusards_%282019%29_Film_Poster.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('All_Together_Now', 'Drama', 'English', 'All_Together_Now.jpg', 'https://m.media-amazon.com/images/M/MV5BZTM4OGY1NDctM2ZiMy00NWZhLThjODktODY1YTczOTdhYzgzXkEyXkFqcGdeQXVyNjEwNTM2Mzc@._V1_.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('I_Am_the_Pretty_Thing_That_Lives_in_the_House', 'Horror', 'English', 'I_Am_the_Pretty_Thing_That_Lives_in_the_House.jpg', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ed/I_Am_the_Pretty_Thing_That_Lives_in_the_House_poster.jpg/220px-I_Am_the_Pretty_Thing_That_Lives_in_the_House_poster.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Rattlesnake', 'Horror', 'English', 'Rattlesnake.jpg', 'https://de.web.img2.acsta.net/pictures/21/06/23/06/09/2724206.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Nobody_Sleeps_in_the_Woods_Tonight', 'Horror', 'Polish', 'Nobody_Sleeps_in_the_Woods_Tonight.jpg', 'https://www.film-rezensionen.de/wp-content/uploads/2020/10/Nobody-Sleeps-in-the-Woods-Tonight-203x300.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('Things_Heard_&_Seen', 'Horror', 'English', 'Things_Heard_&_Seen.jpeg', 'https://de.web.img2.acsta.net/pictures/21/04/09/13/35/2586318.jpg');
    INSERT INTO movies (movie, genre, language, image, linksource) VALUES ('In_the_Tall_Grass', 'Horror', 'English', 'In_the_Tall_Grass.jpeg', 'https://m.media-amazon.com/images/M/MV5BZjA2ZWU3N2MtY2JkYy00YjFjLWEyZWQtMjQ0MTU0NDk1ZTZmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg');




---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: my-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mysql
  template:
    metadata:
      labels:
        app: my-mysql
    spec:

      volumes:
        - name: init-volume
          configMap:
            name: mysql-deployment-init-configmap
      containers:
        - name: my-mysql
          image: mysql
          volumeMounts:
            - name: init-volume
              mountPath: /docker-entrypoint-initdb.d/
          # Set required environment variables to initialize the container
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mysecretpw"
            - name: MYSQL_DATABASE
              value: "popular"
          ports:
            - containerPort: 33060

---
#Begin: Service
apiVersion: v1
kind: Service
metadata:
  name: my-app-mysql-service
spec:
  selector:
    app: my-mysql
  ports:
    - name: mysql-xproto
      protocol: TCP
      port: 33060
      targetPort: 33060
#End: Service
